[build]
  publish = "out"
  command = "npm run build"

[functions]
  directory = "functions/"
  node_bundler = "esbuild"
  included_files = ["resoc-templates/**"]
  external_node_modules = [
    "chrome-aws-lambda",
    "puppeteer-core",
    "@resoc/core",
    "@netlify/functions"
  ]

[[redirects]]
  from = "/templates/:template/content/*"
  to = "resoc-templates/:template/:splat"
  status = 200

[[redirects]]
  from = "/templates/:template/:requestType/:dimensions*"
  to = "/.netlify/functions/image"
  status = 200

[[redirects]]
  from = "/templates"
  to = "/templates-list.json"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
